name: Integration Tests

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    name: Android (integration_test)
    runs-on: self-hosted
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter doctor -v

      - uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}/.dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - run: flutter pub get

      - name: Sanity check emulator
        run: |
          adb start-server || true
          for i in {1..120}; do
            BOOTED=$(adb -s emulator-5554 shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            [ "$BOOTED" = "1" ] && break
            sleep 2
          done
          adb -s emulator-5554 shell settings put global window_animation_scale 0
          adb -s emulator-5554 shell settings put global transition_animation_scale 0
          adb -s emulator-5554 shell settings put global animator_duration_scale 0
          adb devices
          flutter devices

      - name: Run integration tests
        run: flutter test integration_test -d emulator-5554 --coverage

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-lcov
          path: coverage/lcov.info
          if-no-files-found: ignore

      - name: Save logcat
        if: failure()
        run: adb -s emulator-5554 logcat -d > android-logcat.txt || true

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: android-logcat
          path: android-logcat.txt
