name: Integration Tests

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    name: Android (integration_test)
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      # Caches para acelerar builds do app de teste
      - name: Cache pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}/.dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Cache Gradle (Android)
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Pub get
        run: flutter pub get

      # Sobe emulador e executa integração
      - name: Run integration tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33               # Estável nos runners do GitHub; mude para 34 se precisar
          target: google_apis
          arch: x86_64
          profile: pixel_5
          avd-name: ci-android
          force-avd-creation: true    # Evita lixo de runs anteriores
          emulator-boot-timeout: 600000   # 10 min para boot em software render
          disable-animations: true
          emulator-options: >
            -no-window
            -gpu swiftshader_indirect
            -no-snapshot
            -camera-back none
            -camera-front none
            -noaudio
            -no-boot-anim
            -accel off
            -memory 2048
          script: |
            # Sanidade ADB + desbloqueio
            adb kill-server || true
            adb start-server
            adb wait-for-device
            adb devices
            flutter devices
            # Executa os testes (integration_test/)
            flutter test integration_test -d emulator-5554 --coverage

      - name: Upload coverage (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info
          if-no-files-found: ignore

      - name: Save logcat (on failure)
        if: failure()
        run: adb logcat -d > android-logcat.txt || true

      - name: Upload logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: android-logcat
          path: android-logcat.txt
          if-no-files-found: ignore
